sonar.projectKey=chamalkaMarasinghe_event-management-system-api
sonar.organization=chamalkamarasinghe
sonar.projectName=Event Management System API
sonar.host.url=https://sonarcloud.io

# Source directories
sonar.sources=services/api-gateway/src,services/auth-service/src,services/event-service/src,services/notification-service/src

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.js,**/*.spec.js

sonar.sourceEncoding=UTF-8